import { createFileRoute } from "@tanstack/react-router";
import { AppShell, EmptyAnalysis, PageHeader } from "@/components/layout/AppShell";
import { useAnalysis } from "@/hooks/use-analysis";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports — MABI" },
      { name: "description", content: "Analysis reports generated by your agents." },
    ],
  }),
  component: Page,
});

function Page() {
  const { latest } = useAnalysis();
  return (
    <AppShell title="Reports">
      <PageHeader
        title="Reports"
        description="Analysis snapshots generated by your agents. Only your latest completed analysis is stored client-side."
      />
      {!latest ? (
        <EmptyAnalysis label="reports" />
      ) : (
        <div className="rounded-2xl border border-white/5 bg-white/[0.02] overflow-hidden">
          <table className="w-full text-sm">
            <thead className="border-b border-white/5 text-xs uppercase tracking-wider text-muted-foreground">
              <tr>
                <th className="px-6 py-3 text-left font-medium">Report</th>
                <th className="px-6 py-3 text-left font-medium">Company</th>
                <th className="px-6 py-3 text-left font-medium">Industry</th>
                <th className="px-6 py-3 text-left font-medium">Generated</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-white/5">
                <td className="px-6 py-4 font-medium">Multi-agent analysis</td>
                <td className="px-6 py-4">{latest.request.company_name}</td>
                <td className="px-6 py-4 text-muted-foreground">
                  {latest.request.industry}
                </td>
                <td className="px-6 py-4 text-muted-foreground">
                  {new Date(latest.completedAt).toLocaleString()}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      )}
    </AppShell>
  );
}
